<?php

return [
    'vacancy' => [
        'label' => 'Vacancies',
        'description' => 'Vacancies',
        'labels' => [
            'name' => 'Vacancies',
            'singular_name' => 'Vacancy',
            'featured_image' => 'Listing Thumbnail',
            'set_featured_image' => 'Set Listing Thumbnail',
            'remove_featured_image' => 'Remove Listing Thumbnail',
            'use_featured_image' => 'Use as Listing Thumbnail',
            'add_new_item' => 'Add a New Vacancy',
            'edit_item' => 'Edit a Vacancy',
            'not_found' => 'No Vacancies found.',
            'taxonomies' => array('category', 'post_tag')
        ],
        'hierarchical' => true,
        'public' => true,
        'show_ui' => true,
        'show_in_menu' => true,
        'menu_position' => 5,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'can_export' => true,
        'has_archive' => true,
        'exclude_from_search' => true,
        'publicly_queryable' => true,
        'capability_type' => 'post',
        'rewrite' => ['slug' => 'vacancy', 'with_front' => false],
        'menu_icon' => 'dashicons-money',
        'supports' => [
            'excerpt',
            'title',
            'thumbnail',
            'editor',
        ],
    ],
    'team-member' => [
        'label' => 'Team Members',
        'description' => 'Team Member',
        'labels' => [
            'name' => 'Team Members',
            'singular_name' => 'Team Member',
            'featured_image' => 'Member Photo',
            'set_featured_image' => 'Set Member Photo',
            'remove_featured_image' => 'Remove Member Photo',
            'use_featured_image' => 'Use as Member Photo',
            'add_new_item' => 'Add a New Team Member',
            'edit_item' => 'Edit a Team Member',
            'not_found' => 'No Team Members found.',
            'taxonomies' => array('category', 'post_tag')
        ],
        'hierarchical' => true,
        'public' => true,
        'show_ui' => true,
        'show_in_menu' => true,
        'menu_position' => 6,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'can_export' => true,
        'has_archive' => true,
        'exclude_from_search' => true,
        'publicly_queryable' => true,
        'capability_type' => 'post',
        'rewrite' => ['slug' => 'team-member', 'with_front' => false],
        'menu_icon' => 'dashicons-businessman',
        'supports' => [
            'title',
            'thumbnail',
            'editor',
        ],
    ],
    'faq' => [
        'label' => 'FAQs',
        'description' => 'FAQ',
        'labels' => [
            'name' => 'FAQs',
            'singular_name' => 'FAQ',
            'add_new_item' => 'Add a New FAQ',
            'edit_item' => 'Edit a FAQ',
            'not_found' => 'No FAQs found.',
            'taxonomies' => array('faq', 'post_tag')
        ],
        'hierarchical' => true,
        'public' => true,
        'show_ui' => true,
        'show_in_menu' => true,
        'menu_position' => 6,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'can_export' => true,
        'has_archive' => true,
        'exclude_from_search' => true,
        'publicly_queryable' => true,
        'capability_type' => 'post',
        'rewrite' => ['slug' => 'faq', 'with_front' => false],
        'menu_icon' => 'dashicons-editor-help',
        'supports' => [
            'title',
            'editor',
        ],
    ],    
    'white-paper' => [
        'label' => 'White Papers',
        'description' => 'Downloadable Papers',
        'labels' => [
            'name' => 'White Papers',
            'singular_name' => 'White Paper',
            'add_new_item' => 'Add a New White Paper',
            'edit_item' => 'Edit a White Paper',
            'not_found' => 'No White Papers found.',
            'taxonomies' => array('white-paper', 'post_tag')
        ],
        'hierarchical' => true,
        'public' => true,
        'show_ui' => true,
        'show_in_menu' => true,
        'menu_position' => 6,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'can_export' => true,
        'has_archive' => true,
        'exclude_from_search' => true,
        'publicly_queryable' => true,
        'capability_type' => 'post',
        'rewrite' => ['slug' => 'white-paper', 'with_front' => false],
        'menu_icon' => 'dashicons-media-document',
        'supports' => [
            'title',
            'editor',
        ],
    ]         

];
